name: Validate Repository Structure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required folders
        run: |
          test -d docs
          test -d database

      - name: Check required files
        run: |
          test -f docs/ERD.png
          test -f docs/API-Endpoints.md
          test -f database/schema.sql

      - name: Validation successful
        run: echo "Repository structure is valid."
