name: Validate Repository Structure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required folders
        run: |
          test -d docs
          

      - name: Check required files
        run: |
          test -f docs/PROG_ERD.png
          test -f docs/API-Endpoints.md
          test -f docs/schema.sql

      - name: Validation successful
        run: echo "Repository structure is valid."
